### PR TITLE
Remove map usage in decode

### PR DESCRIPTION
**Pull request by varyoo**
Decode will now fail if:
* a dictionary isn't sorted in lexicographical order and it should be
* a dictionary key isn't unique

### CODE REVIEW

**Comment by zeebo** [comment]
I'd prefer to be more permissive in what was accepted. Is it in the specification that bencode decoders must fail in these cases?

**Comment by varyoo** [comment]
Wikipedia says:

> A dictionary is encoded as d<contents>e. The elements of the dictionary are encoded each key immediately followed by its value. **All keys must be byte strings and must appear in lexicographical order**

Also rTorrent will not accept an unordered info dictionary:

https://github.com/rakshasa/libtorrent/blob/c167c5a9e0bcf0df23ae5efd91396aae0e37eb87/src/download/download_constructor.cc#L143

As for the definitions appearing twice, it won't fail anymore because encoding/json doesn't as well (see test in decode_test.go).

**Comment by zeebo** [comment]
It appears that the rTorrent check is after the bencode library, and that the library allows unordered dictionary and leaves it up to callers to ensure that it's ordered.

Can we make the ordering behavior set by some method on the Decoder so that users may opt in to it?

**Comment by varyoo** [comment]
The caller can't ensure that it's ordered. Making it an option means too much code, it's best to drop the PR if you are not sure.

**Comment by zeebo** [comment]
I don’t think it will be too much extra code, so I’ll give it a shot. Thanks for sticking through it.

**Pull request closed without merging**
